/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author hs140
 */
import java.sql.*;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/mydatabase";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "toor";
    Connection conn = null;
    Statement stmt = null;

    public void opendatabase() {
        try {
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL + "?useSSL=false", USER, PASS);
            System.out.println("Connected database successfully...");
            stmt = conn.createStatement();
            String create = "CREATE TABLE IF NOT EXISTS billnow(ID int(5),name varchar(20),phase int(3),prev int(10),pres int(10),unit int(10),cost float(20),PRIMARY KEY (ID))";
            stmt.executeUpdate(create);

        } catch (SQLException se) {
            //Handle errors for JDBC
            System.out.println("Error in sql statement");
        } catch (Exception e) {
            //Handle errors for Class.forName
           System.out.println("Error in Class.forName");
        }
    }
    public void closeconn() {
        int flag=1;
        System.out.println("Closeing connection");
        try {
            if (stmt != null) {
                conn.close();
            }
        } catch (SQLException se) {flag=0;
            System.out.println("Closeing connection error");
        }// do nothing
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException se) {flag=0;
                System.out.println("Closeing connection error");
            se.printStackTrace();
        }
       if(flag!=0)
           System.out.println("Connection Closed!! ");
    }

    public NewJFrame() {

        initComponents();
        opendatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        prefield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        submitfd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        unitfd = new javax.swing.JTextArea();
        confield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        presfd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idfd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        srchfd = new javax.swing.JTextField();
        Srchdisplay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        upprev = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        upnam = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        uppres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        upcon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        upid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrator Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Algerian", 1, 24))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setName(""); // NOI18N

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        submitfd.setText("Submit");
        submitfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitfdActionPerformed(evt);
            }
        });

        unitfd.setColumns(20);
        unitfd.setRows(5);
        jScrollPane2.setViewportView(unitfd);

        jLabel5.setText("Total unit:");

        jLabel3.setText("Prev.reading:");

        jLabel2.setText("Connection(1 or 2):");

        jLabel4.setText("Pres.reading:");

        jLabel1.setText("Name:");

        jLabel6.setText("ID:");

        idfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namefield, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confield)
                            .addComponent(idfd)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(presfd)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(prefield, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(submitfd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(idfd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(confield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(prefield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(presfd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitfd)
                .addGap(36, 36, 36))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Track", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel7.setText("Enter ID :");

        srchfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchfdActionPerformed(evt);
            }
        });

        Srchdisplay.setText("Search");
        Srchdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchdisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srchfd, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(Srchdisplay)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(srchfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Srchdisplay)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Electricity Bill Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18))); // NOI18N

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jLabel8.setText("Made by- ASHAPURA SAHA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(jLabel8)
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel12.setText("Connection:");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Prev.reading:");

        jLabel10.setText("Enter ID :");

        jLabel14.setText("Pres.reading:");

        jLabel11.setText("Name:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upnam, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(upcon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uppres, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(upprev)))
                    .addComponent(upid))
                .addGap(50, 50, 50))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(upid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upprev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uppres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void display(int idd) {
        opendatabase();
        try {
            ResultSet rs = stmt.executeQuery("select * from billnow where id=" + idd);
            rs.next();
            result.setText(" ID: " + rs.getInt(1) + "\n Name: " + rs.getString(2) + "\n phase: " + rs.getInt(3)
                    + "\n Previous meter reading " + rs.getInt(4) + "\n Present meter reading " + rs.getInt(5) + " \n Unit: " + rs.getString(6) + "\n Total Due: " + rs.getFloat(7));
           
        }
        catch (SQLException se) {
            //Handle errors for JDBc
            System.out.println("No record found with id= "+idd);
            result.setText("No record found with id= "+idd);
            
        } finally{
            closeconn();
        }
    }

    public void insert(int id, String nam, int con, int prev, int pres, int unit, float cost) 
    {
opendatabase() ;
int flag=0;
try {
            stmt=conn.createStatement();
            String querry="insert into billnow values("+id+", '"+nam+"'," +con+", "+prev+","+ pres+","+unit+","+cost+")";
            
            stmt.execute(querry);
        } catch (Exception se) {
            //Handle errors for JDBC
             result.setText("Cannot insert");
            System.out.println("Cannot insert");
            flag=1;
        } 
        if(flag!=1)
            display(id);
        
    }

    @SuppressWarnings("empty-statement")
    public float cal_cost(int unit, int phase) {
        float res = (float) 0.00;
        if (phase == 1) {
            if (unit <= 50) {
                res = (float) (unit * 1.45);
            } else if (unit <= 100) {
                res = (float) (50 * 1.45 + (unit - 50) * 2.60);
            } else if (unit <= 200) {
                res = (float) (100 * 3.30 + (unit - 100) * 4.30);
            } else if (unit > 200) {
                res = (float) (200 * 5.00 + (unit - 200) * 6.00);
            }
        } else if (phase == 2) {
            if (unit <= 50) {
                res = (float) (unit * 1.45);
            } else if (unit <= 100) {
                res = (float) (50 * 1.45 + (unit - 50) * 2.60);
            } else if (unit <= 200) {
                res = (float) (100 * 3.30 + (unit - 100) * 4.30);
            } else if (unit > 200) {
                float[] chrg = {5.00f, 7.20f, 8.50f, 9.00f, 9.50f};

                for (int i = 0; i < 4; i++)
                {
                    if (unit > 0) {
                        res += (float) (100 * chrg[i]);
                        unit -= 100;
                    } 
                    else { System.out.println("br");
                        break;
                    }
                }
                if (unit > 0) {
                    res += (float) (unit * chrg[4]);
                }

            }

        }
        return res;
    }

    private void submitfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitfdActionPerformed
        // TODO add your handling code here:
        unitfd.setText("");
      int id=0,connection=0, prev_mr =0,prs_mr=0,flag=0;
        try{
            id = Integer.parseInt(idfd.getText());
        
       }catch (NumberFormatException e) {result.setText("Please provide ID(not empty)");
           System.out.println("Please provide ID (not empty)");
           flag=1;
           }
           if (id==0 && flag!=1)
           {
               System.out.println("Should not be empty.Please enter a valid ID(1,2,3..). ");
           result.setText("Should not be empty.Please enter a valid ID(1,2,3..). ");
           }
           else if ( id!=0)
        {
        String nam = namefield.getText();
        
        
        try{
         connection = Integer.parseInt(confield.getText());
         prev_mr = Integer.parseInt(prefield.getText());
         prs_mr = Integer.parseInt(presfd.getText());
        }catch (NumberFormatException e) {
           System.out.println("Should not be empty.. ");
           result.setText("Should not be empty.. ");
        }
       
        if(prev_mr!=0 && prs_mr!=0 && connection!=0)
        {
        int unit;
        if (prev_mr > prs_mr) {
            unit = prev_mr - prs_mr;
        } else {
            unit = prs_mr - prev_mr;
        }
        unitfd.setText(Integer.toString(unit));

        float cost = (float) (cal_cost(unit, connection));
        insert(id, nam, connection, prev_mr, prs_mr, unit, cost);//connection close insert->display->close()
        }
        
        }

    }//GEN-LAST:event_submitfdActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void idfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfdActionPerformed

    private void srchfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchfdActionPerformed

    private void SrchdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchdisplayActionPerformed
        // TODO add your handling code here:
        int id=0,flag=0;
        try{unitfd.setText("");
         id = Integer.parseInt(srchfd.getText());
        }catch (NumberFormatException e) {result.setText("Please provide ID(not empty)");
           System.out.println("Please provide ID (not empty)");
           flag=1;
           }
           if (id==0 && flag!=1)
           {
               System.out.println("Should not be empty.Please enter a valid ID(1,2,3..). ");
           result.setText("Should not be empty.Please enter a valid ID(1,2,3..). ");
           }
           else if ( id!=0)
            display(id);
        closeconn();
    }//GEN-LAST:event_SrchdisplayActionPerformed

    void updat(int id, String renam, int rename_conn, int rename_prev, int rename_pres)
    { 
        opendatabase();
    
        int ret_prev_mr,ret_prs_mr,ret_connection,ret_unit;
    
         try {
            ResultSet rs = stmt.executeQuery("select * from billnow where id=" + id);
            rs.next();
          //ret=retrieve the previous data on given id
            ret_connection= rs.getInt(3);
            ret_prev_mr = rs.getInt(4);
            ret_prs_mr=rs.getInt(5);
            ret_unit=rs.getInt(6);
            //System.out.println(""+ret_name+ret_connection+ret_prev_mr+ret_prs_mr);
          
            stmt = conn.createStatement();
           String sql;

//String query = " insert into billnow (Id, name, phase, prev, pres,unit,cost)"
      
  if(!renam.equals(""))
       {   
       sql = "UPDATE billnow SET name ='"+renam+"' WHERE id ="+ id;
      stmt.executeUpdate(sql);
        System.out.println(" Name updated ");
        }
          
  if(rename_conn!=0)
       {
         float rename_cost=cal_cost(ret_unit, rename_conn);
        
        sql = "UPDATE billnow SET phase ="+rename_conn+",cost="+rename_cost+" WHERE id ="+ id;
      stmt.executeUpdate(sql);
      System.out.println(" Connection updated");
       }
          
  if(rename_prev!=0)
       {
           int new_unit;
           if(rename_prev>=ret_prs_mr)
               new_unit=rename_prev-ret_prs_mr;
           else
               new_unit=ret_prs_mr-rename_prev;
           float rename_cost=cal_cost(new_unit, ret_connection);
       sql = "UPDATE billnow SET prev ="+rename_prev+",unit="+new_unit+",cost="+rename_cost+"WHERE id ="+ id;
      stmt.executeUpdate(sql);
      System.out.println(" Prev reading updated");
        }
             
  if(rename_pres!=0)
       {
     int new_unit;
           if(ret_prev_mr>=rename_pres)
               new_unit=ret_prev_mr-rename_pres;
           else
               new_unit=rename_pres-ret_prev_mr;
           float rename_cost=cal_cost(new_unit, ret_connection);
       sql = "UPDATE billnow SET pres ="+rename_pres+",unit="+new_unit+", cost="+rename_cost+"WHERE id ="+ id;
      stmt.executeUpdate(sql);
      System.out.println(" Present reading updated");
        }
           
        } catch (SQLException se) {
              result.setText("Cannot update.. Is this ID="+id+" is already present in database??");
            System.out.println("Cannot update.. Is this ID="+id+" is already present in database??");
            
        } catch (Exception e) {
            System.out.println("Cannot update");
            
        }finally{
             closeconn();
         }
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        unitfd.setText("");
        int prev_mr,prs_mr,connection;
        int id=0,flag=0;
      
           try{ id = Integer.parseInt(upid.getText());
           }catch(NumberFormatException e)
           { //for no input (id="")
               result.setText("Please provide ID(not empty)");
           System.out.println("Please provide ID (not empty)");
           flag=1;
           }
           if (id==0 && flag!=1)
           {
               System.out.println("Should not be empty.Please enter a valid ID(1,2,3..). ");
           result.setText("Should not be empty.Please enter a valid ID(1,2,3..). ");
           }
           else if ( id!=0)
       {
        String nam = upnam.getText();
      
        try{
            connection = Integer.parseInt(upcon.getText());
        }catch(NumberFormatException n)
       {
           connection=0;
       }
        
        try{
         prev_mr = Integer.parseInt(upprev.getText());
        }catch(NumberFormatException n)
       {
           prev_mr=0 ;
       }
        
        try{
         prs_mr = Integer.parseInt(uppres.getText());
        }catch(NumberFormatException n)
       {
           prs_mr=0;
       }
        
        //System.out.println(""+nam+connection+prev_mr+prs_mr);
        updat(id, nam, connection, prev_mr, prs_mr);
       }
      
       
           closeconn();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {//1. main
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //2. creation of frame
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Srchdisplay;
    private javax.swing.JTextField confield;
    private javax.swing.JTextField idfd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField prefield;
    private javax.swing.JTextField presfd;
    private javax.swing.JTextArea result;
    private javax.swing.JTextField srchfd;
    private javax.swing.JButton submitfd;
    private javax.swing.JTextArea unitfd;
    private javax.swing.JTextField upcon;
    private javax.swing.JTextField upid;
    private javax.swing.JTextField upnam;
    private javax.swing.JTextField uppres;
    private javax.swing.JTextField upprev;
    // End of variables declaration//GEN-END:variables
}
